"""
Models package for API request/response schemas.
"""

from .common import (
    BaseRequest,
    BaseResponse,
    ErrorResponse,
    HealthResponse,
    StorageInfo,
)
from .requests import (
    InitializeSessionRequest,
    SetLearningGoalRequest,
    SessionCompleteRequest,
    GetDashboardRequest,
    GetProfileRequest,
    GetLearnerMemoryRequest,
    SearchHistoryRequest,
    ChatWithTutorRequest,
    LearningGoalRefinementRequest,
    SkillGapIdentificationRequest,
    LearnerProfileInitializationWithInfoRequest,
    LearnerProfileInitializationRequest,
    LearnerProfileUpdateRequest,
    LearningPathSchedulingRequest,
    LearningPathReschedulingRequest,
    KnowledgePointExplorationRequest,
    KnowledgePointDraftingRequest,
    KnowledgePointsDraftingRequest,
    LearningDocumentIntegrationRequest,
    KnowledgeQuizGenerationRequest,
    TailoredContentGenerationRequest,
    HistorySearchRequest,
    PerformanceEvaluationRequest,
    SkillMasteryEvaluationRequest,
    PerformanceReportRequest,
    FeedbackSimulationRequest,
)
from .responses import (
    InitializeSessionResponse,
    DashboardResponse,
    SessionCompleteResponse,
    ChatResponse,
    RefinedGoalResponse,
    SkillGapResponse,
    LearnerProfileResponse,
    LearningPathResponse,
    KnowledgePointsResponse,
    KnowledgeDraftResponse,
    KnowledgeDraftsResponse,
    LearningDocumentResponse,
    QuizResponse,
    TailoredContentResponse,
    LearnerMemoryResponse,
    HistorySearchResponse,
    LLMModel,
    LLMModelsResponse,
    PerformanceEvaluationResponse,
    SkillMasteryEvaluationResponse,
    PerformanceReportResponse,
    FeedbackSimulationResponse,
    GoalsListResponse,
    GoalDetailResponse,
)

__all__ = [
    # Common
    "BaseRequest",
    "BaseResponse",
    "ErrorResponse",
    "HealthResponse",
    "StorageInfo",
    # Session Management Requests
    "InitializeSessionRequest",
    "SetLearningGoalRequest",
    "SessionCompleteRequest",
    "GetDashboardRequest",
    "GetProfileRequest",
    "GetLearnerMemoryRequest",
    "SearchHistoryRequest",
    # Requests
    "ChatWithTutorRequest",
    "LearningGoalRefinementRequest",
    "SkillGapIdentificationRequest",
    "LearnerProfileInitializationWithInfoRequest",
    "LearnerProfileInitializationRequest",
    "LearnerProfileUpdateRequest",
    "LearningPathSchedulingRequest",
    "LearningPathReschedulingRequest",
    "KnowledgePointExplorationRequest",
    "KnowledgePointDraftingRequest",
    "KnowledgePointsDraftingRequest",
    "LearningDocumentIntegrationRequest",
    "KnowledgeQuizGenerationRequest",
    "TailoredContentGenerationRequest",
    "HistorySearchRequest",
    # Assessment Requests
    "PerformanceEvaluationRequest",
    "SkillMasteryEvaluationRequest",
    "PerformanceReportRequest",
    "FeedbackSimulationRequest",
    # Session Management Responses
    "InitializeSessionResponse",
    "DashboardResponse",
    "SessionCompleteResponse",
    # Responses
    "ChatResponse",
    "RefinedGoalResponse",
    "SkillGapResponse",
    "LearnerProfileResponse",
    "LearningPathResponse",
    "KnowledgePointsResponse",
    "KnowledgeDraftResponse",
    "KnowledgeDraftsResponse",
    "LearningDocumentResponse",
    "QuizResponse",
    "TailoredContentResponse",
    "LearnerMemoryResponse",
    "HistorySearchResponse",
    "LLMModel",
    "LLMModelsResponse",
    # Assessment Responses
    "PerformanceEvaluationResponse",
    "SkillMasteryEvaluationResponse",
    "PerformanceReportResponse",
    "FeedbackSimulationResponse",
    # Goal Responses
    "GoalsListResponse",
    "GoalDetailResponse",
]
